permalink: /:year/:month/:day/:title.html
markdown: redcarpet
comments: true

# Author settings
author:
  name: Mars Ma
  email: wenchma@gmail.com
  link: https://wenchma.github.io
  weibo: http://weibo.com/wenchma
  github: http://github.com/wenchma

# Site settings
title: Mars's Blog
logo: /img/logo.png
email: wenchma@gmail.com
description: Mars's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wenchma.github.io" # the base hostname & protocol for your site
rss_url: /pages/atom.xml
twitter_username: wenchma
github_username:  wenchma

# paginate settings
paginate: 10
paginate_path: "/page:num/"

# Build settings
markdown: kramdown

disqus:
  shortname: wenchma

locals:
  tech: Tech
  life: Life
  tags: Tags
  about: About
  newest: 最新文章
  archive: Archive

gems:
  - jemoji
#  - jekyll-paginate
